### ISSUE TITLE
Why is that?，can you tell me ,Thank you!

### ISSUE THREAD

**Issue by yaqi-Wang** [benfulcher/hctsa_phenotypingFly#4]
Hello Sir, this result of you gives me a good understanding of HCTSA, but I get this error when I run the code, showing HCTSA_FILTERConstant.MAT not found;
            % Load data from the file:
            if ~exist(whatDataFile,'file')
                error('%s not found',whatDataFile);
            end
            fprintf(1,'Loading data from %s...',whatDataFile);
            load(whatDataFile,'TS_DataMat','Operations','TimeSeries');
            fprintf(1,' Done.\n');
Why is that?，can you tell me ,Thank you!

**Comment by benfulcher** [comment]
Please provide information about what code you ran (from what function) so that the error can be reproduced. It seems like you've set `whatDataFile = HCTSA_FILTERConstant.MAT` but this file doesn't exist, so the first `~exist` error is being triggered.

**Comment by yaqi-Wang** [comment]
Hello sir，
    Please forgive me for not responding to your email in time, I ran this code, that the github address：https://github.com/benfulcher/hctsa_phenotypingWorm. I want run 'paperMainTextFigures'. Thank you,sir.

**Comment by benfulcher** [comment]
Then this issue is not relevant to this repository. I have just checked that this function works if you have correctly followed the instructions (the hctsa data need to be downloaded first). If your problems persist, please leave a detailed description of what code you ran and what error you obtained on the appropriate repository.
